/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard.dashboard.index'
import { Route as ApiAiTestConnectionRouteImport } from './routes/api.ai.test-connection'
import { Route as ApiAiStatusRouteImport } from './routes/api.ai.status'
import { Route as ApiAiSearchRouteImport } from './routes/api.ai.search'
import { Route as ApiAiModelsRouteImport } from './routes/api.ai.models'
import { Route as ApiAiConfigStoreRouteImport } from './routes/api.ai.config-store'
import { Route as ApiAiChatRouteImport } from './routes/api.ai.chat'
import { Route as ApiAiAuditRouteImport } from './routes/api.ai.audit'
import { Route as DashboardDashboardUsersRouteImport } from './routes/_dashboard.dashboard.users'
import { Route as DashboardDashboardTransactionsRouteImport } from './routes/_dashboard.dashboard.transactions'
import { Route as DashboardDashboardTodosRouteImport } from './routes/_dashboard.dashboard.todos'
import { Route as DashboardDashboardTeamRouteImport } from './routes/_dashboard.dashboard.team'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard.dashboard.settings'
import { Route as DashboardDashboardProjectsRouteImport } from './routes/_dashboard.dashboard.projects'
import { Route as DashboardDashboardHelpRouteImport } from './routes/_dashboard.dashboard.help'
import { Route as DashboardDashboardCategoriesRouteImport } from './routes/_dashboard.dashboard.categories'
import { Route as DashboardDashboardAnalyticsRouteImport } from './routes/_dashboard.dashboard.analytics'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard.dashboard.settings.index'
import { Route as ApiAiChatCompletionsRouteImport } from './routes/api.ai.chat.completions'
import { Route as DashboardDashboardSettingsSystemRouteImport } from './routes/_dashboard.dashboard.settings.system'
import { Route as DashboardDashboardSettingsIa_configRouteImport } from './routes/_dashboard.dashboard.settings.ia_config'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const ApiAiTestConnectionRoute = ApiAiTestConnectionRouteImport.update({
  id: '/api/ai/test-connection',
  path: '/api/ai/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiModelsRoute = ApiAiModelsRouteImport.update({
  id: '/api/ai/models',
  path: '/api/ai/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigStoreRoute = ApiAiConfigStoreRouteImport.update({
  id: '/api/ai/config-store',
  path: '/api/ai/config-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAuditRoute = ApiAiAuditRouteImport.update({
  id: '/api/ai/audit',
  path: '/api/ai/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardUsersRoute = DashboardDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardTransactionsRoute =
  DashboardDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardTodosRoute = DashboardDashboardTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardTeamRoute = DashboardDashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardProjectsRoute =
  DashboardDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardHelpRoute = DashboardDashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardCategoriesRoute =
  DashboardDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardAnalyticsRoute =
  DashboardDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardSettingsRoute,
  } as any)
const ApiAiChatCompletionsRoute = ApiAiChatCompletionsRouteImport.update({
  id: '/completions',
  path: '/completions',
  getParentRoute: () => ApiAiChatRoute,
} as any)
const DashboardDashboardSettingsSystemRoute =
  DashboardDashboardSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => DashboardDashboardSettingsRoute,
  } as any)
const DashboardDashboardSettingsIa_configRoute =
  DashboardDashboardSettingsIa_configRouteImport.update({
    id: '/ia_config',
    path: '/ia_config',
    getParentRoute: () => DashboardDashboardSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsRoute
  '/dashboard/categories': typeof DashboardDashboardCategoriesRoute
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/projects': typeof DashboardDashboardProjectsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRouteWithChildren
  '/dashboard/team': typeof DashboardDashboardTeamRoute
  '/dashboard/todos': typeof DashboardDashboardTodosRoute
  '/dashboard/transactions': typeof DashboardDashboardTransactionsRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsRoute
  '/dashboard/categories': typeof DashboardDashboardCategoriesRoute
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/projects': typeof DashboardDashboardProjectsRoute
  '/dashboard/team': typeof DashboardDashboardTeamRoute
  '/dashboard/todos': typeof DashboardDashboardTodosRoute
  '/dashboard/transactions': typeof DashboardDashboardTransactionsRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/dashboard/analytics': typeof DashboardDashboardAnalyticsRoute
  '/_dashboard/dashboard/categories': typeof DashboardDashboardCategoriesRoute
  '/_dashboard/dashboard/help': typeof DashboardDashboardHelpRoute
  '/_dashboard/dashboard/projects': typeof DashboardDashboardProjectsRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRouteWithChildren
  '/_dashboard/dashboard/team': typeof DashboardDashboardTeamRoute
  '/_dashboard/dashboard/todos': typeof DashboardDashboardTodosRoute
  '/_dashboard/dashboard/transactions': typeof DashboardDashboardTransactionsRoute
  '/_dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/_dashboard/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/help'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/todos'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/chat'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/dashboard/'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/help'
    | '/dashboard/projects'
    | '/dashboard/team'
    | '/dashboard/todos'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/chat'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/dashboard'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/_dashboard/dashboard'
    | '/_landing/'
    | '/_dashboard/dashboard/analytics'
    | '/_dashboard/dashboard/categories'
    | '/_dashboard/dashboard/help'
    | '/_dashboard/dashboard/projects'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/team'
    | '/_dashboard/dashboard/todos'
    | '/_dashboard/dashboard/transactions'
    | '/_dashboard/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/chat'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/settings/ia_config'
    | '/_dashboard/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/_dashboard/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  ApiAiAuditRoute: typeof ApiAiAuditRoute
  ApiAiChatRoute: typeof ApiAiChatRouteWithChildren
  ApiAiConfigStoreRoute: typeof ApiAiConfigStoreRoute
  ApiAiModelsRoute: typeof ApiAiModelsRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAiTestConnectionRoute: typeof ApiAiTestConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/api/ai/test-connection': {
      id: '/api/ai/test-connection'
      path: '/api/ai/test-connection'
      fullPath: '/api/ai/test-connection'
      preLoaderRoute: typeof ApiAiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/models': {
      id: '/api/ai/models'
      path: '/api/ai/models'
      fullPath: '/api/ai/models'
      preLoaderRoute: typeof ApiAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config-store': {
      id: '/api/ai/config-store'
      path: '/api/ai/config-store'
      fullPath: '/api/ai/config-store'
      preLoaderRoute: typeof ApiAiConfigStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/audit': {
      id: '/api/ai/audit'
      path: '/api/ai/audit'
      fullPath: '/api/ai/audit'
      preLoaderRoute: typeof ApiAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/users': {
      id: '/_dashboard/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardDashboardUsersRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/transactions': {
      id: '/_dashboard/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardDashboardTransactionsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/todos': {
      id: '/_dashboard/dashboard/todos'
      path: '/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardDashboardTodosRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/team': {
      id: '/_dashboard/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardDashboardTeamRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/projects': {
      id: '/_dashboard/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardDashboardProjectsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/help': {
      id: '/_dashboard/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardDashboardHelpRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/categories': {
      id: '/_dashboard/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardDashboardCategoriesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/analytics': {
      id: '/_dashboard/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardDashboardAnalyticsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardDashboardSettingsRoute
    }
    '/api/ai/chat/completions': {
      id: '/api/ai/chat/completions'
      path: '/completions'
      fullPath: '/api/ai/chat/completions'
      preLoaderRoute: typeof ApiAiChatCompletionsRouteImport
      parentRoute: typeof ApiAiChatRoute
    }
    '/_dashboard/dashboard/settings/system': {
      id: '/_dashboard/dashboard/settings/system'
      path: '/system'
      fullPath: '/dashboard/settings/system'
      preLoaderRoute: typeof DashboardDashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardDashboardSettingsRoute
    }
    '/_dashboard/dashboard/settings/ia_config': {
      id: '/_dashboard/dashboard/settings/ia_config'
      path: '/ia_config'
      fullPath: '/dashboard/settings/ia_config'
      preLoaderRoute: typeof DashboardDashboardSettingsIa_configRouteImport
      parentRoute: typeof DashboardDashboardSettingsRoute
    }
  }
}

interface DashboardDashboardSettingsRouteChildren {
  DashboardDashboardSettingsIa_configRoute: typeof DashboardDashboardSettingsIa_configRoute
  DashboardDashboardSettingsSystemRoute: typeof DashboardDashboardSettingsSystemRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
}

const DashboardDashboardSettingsRouteChildren: DashboardDashboardSettingsRouteChildren =
  {
    DashboardDashboardSettingsIa_configRoute:
      DashboardDashboardSettingsIa_configRoute,
    DashboardDashboardSettingsSystemRoute:
      DashboardDashboardSettingsSystemRoute,
    DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  }

const DashboardDashboardSettingsRouteWithChildren =
  DashboardDashboardSettingsRoute._addFileChildren(
    DashboardDashboardSettingsRouteChildren,
  )

interface DashboardDashboardRouteChildren {
  DashboardDashboardAnalyticsRoute: typeof DashboardDashboardAnalyticsRoute
  DashboardDashboardCategoriesRoute: typeof DashboardDashboardCategoriesRoute
  DashboardDashboardHelpRoute: typeof DashboardDashboardHelpRoute
  DashboardDashboardProjectsRoute: typeof DashboardDashboardProjectsRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRouteWithChildren
  DashboardDashboardTeamRoute: typeof DashboardDashboardTeamRoute
  DashboardDashboardTodosRoute: typeof DashboardDashboardTodosRoute
  DashboardDashboardTransactionsRoute: typeof DashboardDashboardTransactionsRoute
  DashboardDashboardUsersRoute: typeof DashboardDashboardUsersRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardAnalyticsRoute: DashboardDashboardAnalyticsRoute,
  DashboardDashboardCategoriesRoute: DashboardDashboardCategoriesRoute,
  DashboardDashboardHelpRoute: DashboardDashboardHelpRoute,
  DashboardDashboardProjectsRoute: DashboardDashboardProjectsRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRouteWithChildren,
  DashboardDashboardTeamRoute: DashboardDashboardTeamRoute,
  DashboardDashboardTodosRoute: DashboardDashboardTodosRoute,
  DashboardDashboardTransactionsRoute: DashboardDashboardTransactionsRoute,
  DashboardDashboardUsersRoute: DashboardDashboardUsersRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LandingRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface ApiAiChatRouteChildren {
  ApiAiChatCompletionsRoute: typeof ApiAiChatCompletionsRoute
}

const ApiAiChatRouteChildren: ApiAiChatRouteChildren = {
  ApiAiChatCompletionsRoute: ApiAiChatCompletionsRoute,
}

const ApiAiChatRouteWithChildren = ApiAiChatRoute._addFileChildren(
  ApiAiChatRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  ApiAiAuditRoute: ApiAiAuditRoute,
  ApiAiChatRoute: ApiAiChatRouteWithChildren,
  ApiAiConfigStoreRoute: ApiAiConfigStoreRoute,
  ApiAiModelsRoute: ApiAiModelsRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAiTestConnectionRoute: ApiAiTestConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
